name: test
on:
  workflow_dispatch:
jobs:
    job1:
        name: First
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v2
            - run: echo "Step1"
    job2:
        name: Second
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v2
            - run: echo "Step2"
            
    job3:
        name: third
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v2
            - run: echo "Step3"
   
