name: test
on: push
jobs:
    job1:
        name: First
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v2
            - run: echo "Step1"
    job2:
        name: Second
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v2
            - run: echo "Step2"
   
